[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = { version = "1.0", features = ["spin_no_std"] }
spin = "0.5.2"
time = { version = "0.3.39", features = [
	"alloc",
	"macros",
], default-features = false }
uart_16550 = "0.2.0"
x86_64 = "0.14.2"
